// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.8
// source: messages/forecast.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Forecast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefTime      int64             `protobuf:"varint,1,opt,name=ref_time,json=refTime,proto3" json:"ref_time,omitempty"`
	ForecastTime int64             `protobuf:"varint,2,opt,name=forecast_time,json=forecastTime,proto3" json:"forecast_time,omitempty"`
	Url          string            `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	DataInfo     *DataInfo         `protobuf:"bytes,4,opt,name=data_info,json=dataInfo,proto3" json:"data_info,omitempty"`
	Levels       []string          `protobuf:"bytes,5,rep,name=levels,proto3" json:"levels,omitempty"`
	Data         []*CoordinateData `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *Forecast) Reset() {
	*x = Forecast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_forecast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forecast) ProtoMessage() {}

func (x *Forecast) ProtoReflect() protoreflect.Message {
	mi := &file_messages_forecast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forecast.ProtoReflect.Descriptor instead.
func (*Forecast) Descriptor() ([]byte, []int) {
	return file_messages_forecast_proto_rawDescGZIP(), []int{0}
}

func (x *Forecast) GetRefTime() int64 {
	if x != nil {
		return x.RefTime
	}
	return 0
}

func (x *Forecast) GetForecastTime() int64 {
	if x != nil {
		return x.ForecastTime
	}
	return 0
}

func (x *Forecast) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Forecast) GetDataInfo() *DataInfo {
	if x != nil {
		return x.DataInfo
	}
	return nil
}

func (x *Forecast) GetLevels() []string {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *Forecast) GetData() []*CoordinateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DataInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatMin     float64 `protobuf:"fixed64,1,opt,name=lat_min,json=latMin,proto3" json:"lat_min,omitempty"`
	LatMax     float64 `protobuf:"fixed64,2,opt,name=lat_max,json=latMax,proto3" json:"lat_max,omitempty"`
	LongMin    float64 `protobuf:"fixed64,3,opt,name=long_min,json=longMin,proto3" json:"long_min,omitempty"`
	LongMax    float64 `protobuf:"fixed64,4,opt,name=long_max,json=longMax,proto3" json:"long_max,omitempty"`
	Resolution float64 `protobuf:"fixed64,5,opt,name=resolution,proto3" json:"resolution,omitempty"`
}

func (x *DataInfo) Reset() {
	*x = DataInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_forecast_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInfo) ProtoMessage() {}

func (x *DataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_forecast_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInfo.ProtoReflect.Descriptor instead.
func (*DataInfo) Descriptor() ([]byte, []int) {
	return file_messages_forecast_proto_rawDescGZIP(), []int{1}
}

func (x *DataInfo) GetLatMin() float64 {
	if x != nil {
		return x.LatMin
	}
	return 0
}

func (x *DataInfo) GetLatMax() float64 {
	if x != nil {
		return x.LatMax
	}
	return 0
}

func (x *DataInfo) GetLongMin() float64 {
	if x != nil {
		return x.LongMin
	}
	return 0
}

func (x *DataInfo) GetLongMax() float64 {
	if x != nil {
		return x.LongMax
	}
	return 0
}

func (x *DataInfo) GetResolution() float64 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

type CoordinateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Values    []*Value `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *CoordinateData) Reset() {
	*x = CoordinateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_forecast_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoordinateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateData) ProtoMessage() {}

func (x *CoordinateData) ProtoReflect() protoreflect.Message {
	mi := &file_messages_forecast_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateData.ProtoReflect.Descriptor instead.
func (*CoordinateData) Descriptor() ([]byte, []int) {
	return file_messages_forecast_proto_rawDescGZIP(), []int{2}
}

func (x *CoordinateData) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CoordinateData) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CoordinateData) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TMP  *float32 `protobuf:"fixed32,1,opt,name=TMP,proto3,oneof" json:"TMP,omitempty"`
	VGRD *float32 `protobuf:"fixed32,2,opt,name=VGRD,proto3,oneof" json:"VGRD,omitempty"`
	UGRD *float32 `protobuf:"fixed32,3,opt,name=UGRD,proto3,oneof" json:"UGRD,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_forecast_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_messages_forecast_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_messages_forecast_proto_rawDescGZIP(), []int{3}
}

func (x *Value) GetTMP() float32 {
	if x != nil && x.TMP != nil {
		return *x.TMP
	}
	return 0
}

func (x *Value) GetVGRD() float32 {
	if x != nil && x.VGRD != nil {
		return *x.VGRD
	}
	return 0
}

func (x *Value) GetUGRD() float32 {
	if x != nil && x.UGRD != nil {
		return *x.UGRD
	}
	return 0
}

var File_messages_forecast_proto protoreflect.FileDescriptor

var file_messages_forecast_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x66, 0x6f, 0x72, 0x65, 0x63,
	0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x01, 0x0a, 0x08, 0x46, 0x6f,
	0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x66, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x66, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x6f, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x66, 0x6f, 0x72, 0x65, 0x63, 0x61,
	0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x92, 0x01,
	0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x61,
	0x74, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6c, 0x61, 0x74,
	0x4d, 0x69, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x61, 0x74, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6c, 0x61, 0x74, 0x4d, 0x61, 0x78, 0x12, 0x19, 0x0a, 0x08,
	0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07,
	0x6c, 0x6f, 0x6e, 0x67, 0x4d, 0x69, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x6e, 0x67, 0x5f,
	0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x4d,
	0x61, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x6a, 0x0a, 0x0e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1e,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x6a,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x15, 0x0a, 0x03, 0x54, 0x4d, 0x50, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x03, 0x54, 0x4d, 0x50, 0x88, 0x01, 0x01, 0x12, 0x17,
	0x0a, 0x04, 0x56, 0x47, 0x52, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x04,
	0x56, 0x47, 0x52, 0x44, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x55, 0x47, 0x52, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x02, 0x52, 0x04, 0x55, 0x47, 0x52, 0x44, 0x88, 0x01, 0x01,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x54, 0x4d, 0x50, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x56, 0x47, 0x52,
	0x44, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x55, 0x47, 0x52, 0x44, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_messages_forecast_proto_rawDescOnce sync.Once
	file_messages_forecast_proto_rawDescData = file_messages_forecast_proto_rawDesc
)

func file_messages_forecast_proto_rawDescGZIP() []byte {
	file_messages_forecast_proto_rawDescOnce.Do(func() {
		file_messages_forecast_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_forecast_proto_rawDescData)
	})
	return file_messages_forecast_proto_rawDescData
}

var file_messages_forecast_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_messages_forecast_proto_goTypes = []interface{}{
	(*Forecast)(nil),       // 0: Forecast
	(*DataInfo)(nil),       // 1: DataInfo
	(*CoordinateData)(nil), // 2: CoordinateData
	(*Value)(nil),          // 3: Value
}
var file_messages_forecast_proto_depIdxs = []int32{
	1, // 0: Forecast.data_info:type_name -> DataInfo
	2, // 1: Forecast.data:type_name -> CoordinateData
	3, // 2: CoordinateData.values:type_name -> Value
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_messages_forecast_proto_init() }
func file_messages_forecast_proto_init() {
	if File_messages_forecast_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_forecast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forecast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_forecast_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_forecast_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoordinateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_forecast_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messages_forecast_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_forecast_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_forecast_proto_goTypes,
		DependencyIndexes: file_messages_forecast_proto_depIdxs,
		MessageInfos:      file_messages_forecast_proto_msgTypes,
	}.Build()
	File_messages_forecast_proto = out.File
	file_messages_forecast_proto_rawDesc = nil
	file_messages_forecast_proto_goTypes = nil
	file_messages_forecast_proto_depIdxs = nil
}
